// 現在格納されている出力を確認
SELECT FULL_TEXT FROM SECURITIES_REPORTS_TEXT LIMIT 1;

// pdfのテキスト化処理を確認
SELECT AI_PARSE_DOCUMENT(
  TO_FILE('@SECURITIES_REPORTS', '有価証券報告書（12044）.pdf'),
  OBJECT_CONSTRUCT('mode','LAYOUT', 'page_split', TRUE)
);
SELECT AI_PARSE_DOCUMENT(
  TO_FILE('@SECURITIES_REPORTS', '有価証券報告書（12044）.pdf'),
  OBJECT_CONSTRUCT('mode','OCR', 'page_split', TRUE)
);
// 一番後続の処理が行いやすそうな出力
SELECT AI_PARSE_DOCUMENT(
  TO_FILE('@SECURITIES_REPORTS', '有価証券報告書（12044）.pdf'),
  OBJECT_CONSTRUCT('mode','LAYOUT', 'page_split', FALSE)
);


SELECT * FROM SECURITIES_REPORTS_CHUNKS LIMIT 10;


SELECT COMPANY_CODE, CHUNK_ID, L1_TITLE, L2_TITLE, CHUNK_TEXT, CHAR_COUNT FROM SECURITIES_REPORTS_CHUNKS WHERE COMPANY_CODE = '12044' ORDER BY CHUNK_ID;

SELECT COMPANY_CODE, CHUNK_ID, L1_TITLE, L2_TITLE, CHUNK_TEXT, CHAR_COUNT FROM SECURITIES_REPORTS_CHUNKS WHERE L2_TITLE = 'None';

CREATE OR REPLACE TABLE SECURITIES_REPORTS_CHUNKS_ARRANGE AS
SELECT
    COMPANY_CODE
    ,CHUNK_ID
    ,CASE
        WHEN L2_TITLE = 'None' THEN L1_TITLE || CHUNK_TEXT
        ELSE L1_TITLE || L2_TITLE || CHUNK_TEXT
    END AS CHUNK_TEXT_ARRANGE
    ,CHAR_COUNT
    ,START_POS
    ,END_POS
    ,DOCUMENT_TITLE
    ,SUBMISSION_DATE
    ,FISCAL_PERIOD
    ,FISCAL_YEAR
    ,PAGE_COUNT
    ,PDF_FILE_NAME
    ,STAGE_PATH
    ,EXTRACTION_METHOD
    ,EXTRACTION_TIMESTAMP
FROM SECURITIES_REPORTS_CHUNKS
;
